### ISSUE TITLE
UTM-Snapshot-Manager only supports QCOW2?

### ISSUE THREAD

**Issue by itababa** [Metamogul/UTM-Snapshot-Manager#9]
By trial and error, found out I couldn't take a snapshot of a UTM VM that had a .img disk image.
Is there any functional reason why it doesn't support IMG files?
Thanks!

**Comment by Metamogul** [comment]
Thanks for reporting, @itababa! As the [README.md](README.md) explains, this tool is nothing but a fancy frontend for `qemu-img`, a disk management utility that is part of the `qemu` hypervisor which UTM mainly leverages to create VMs. `qemu` has snapshot-functionality for `.qcow` images built in, however not for raw images. I've amended the README.md to reflect this.
